docker exec scheduler mkdir -p /opt/scripts/userjourneys/BrowserAutomation/jw/com/
docker exec scheduler mkdir -p /opt/scripts/userjourneys/BrowserAutomation/jw/ie/
docker exec scheduler mkdir -p /opt/scripts/userjourneys/BrowserAutomation/jw/dev/
docker exec scheduler mkdir -p /opt/scripts/userjourneys/BrowserAutomation/arg/dev/
docker exec scheduler mkdir -p /opt/scripts/userjourneys/BrowserAutomation/arg/ar/
docker exec scheduler mkdir -p /opt/scripts/userjourneys/BrowserAutomation/csg/wh/
docker exec scheduler mkdir -p /opt/scripts/userjourneys/BrowserAutomation/csg/bb/

docker cp jw/com/journey.conf scheduler:/opt/scripts/userjourneys/BrowserAutomation/jw/com/
docker cp jw/ie/journey.conf scheduler:/opt/scripts/userjourneys/BrowserAutomation/jw/ie/
docker cp jw/dev/journey.conf scheduler:/opt/scripts/userjourneys/BrowserAutomation/jw/dev/
docker cp arg/dev/journey.conf scheduler:/opt/scripts/userjourneys/BrowserAutomation/arg/dev/
docker cp arg/ar/journey.conf scheduler:/opt/scripts/userjourneys/BrowserAutomation/arg/ar/
docker cp csg/wh/journey.conf scheduler:/opt/scripts/userjourneys/BrowserAutomation/csg/wh/
docker cp csg/bb/journey.conf scheduler:/opt/scripts/userjourneys/BrowserAutomation/csg/bb/

docker cp synthetic-user-journey.py scheduler:/opt/scripts/userjourneys/BrowserAutomation/
docker cp crontab scheduler:/opt/scripts/userjourneys/BrowserAutomation/

docker exec scheduler crontab /opt/scripts/userjourneys/BrowserAutomation/crontab
docker exec scheduler service crond restart
